task2/Trukhan.TicketReSailing/Trukhan.TicketReSailing.Presentation/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System;
using System.Security.Claims;
using Trukhan.TicketReSailing.Business.Interfaces;
using Trukhan.TicketReSailing.Business.Models;


namespace Trukhan.TicketReSailing.Presentation.Controllers
{
    public class HomeController : Controller
    {
        public HomeController(IEventRepository eventRepository, IStringLocalizer<HomeController> localizer)
        {
            _eventRepository = eventRepository;
            _localizer = localizer;
        }

        public IEventRepository _eventRepository { get; set; }

        private IStringLocalizer<HomeController> _localizer;

        public IActionResult Index()
        {
            ViewBag.NamePage = _localizer["Events"];
            return View(_eventRepository);
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            CookiesCulture.SetCookiesCulture(Response, culture);
            return LocalRedirect(returnUrl);
        }
    }
}

task2/Trukhan.TicketReSailing/Trukhan.TicketReSailing.Presentation/Controllers/TicketController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Trukhan.TicketReSailing.Business.Models;
using Microsoft.Extensions.Localization;
using Trukhan.TicketReSailing.Business.Interfaces;
using Microsoft.AspNetCore.Authorization;
using System.Linq;

namespace Trukhan.TicketReSailing.Presentation.Controllers
{

    public class TicketController : Controller
    {
        public TicketController(IStringLocalizer<TicketController> localizer, ITicketsRepository ticketsRepository, IUserRepository users, IOrdersRepository ordersRepository)
        {
            _localizer = localizer;
            _ticketsRepository = ticketsRepository;
            _ordersRepository = ordersRepository;
            _users = users;
        }

        private IStringLocalizer<TicketController> _localizer;
        private ITicketsRepository _ticketsRepository;
        private IOrdersRepository _ordersRepository;
        private IUserRepository _users;

        [HttpGet]
        public IActionResult ListTickets(int eventId)
        {
            ViewBag.NamePage = _localizer["List tickets"];
            List<Ticket> ticketsEvent = _ticketsRepository.FindByEventID(eventId);
            return View(ticketsEvent);
        }

        [Authorize]
        public IActionResult GetMyTickets()
        {
            ViewBag.NamePage = _localizer["My tickets"];
            List<Ticket> myTickets = _ticketsRepository.FindBySellerName(User.Identity.Name);
            return View(myTickets);
        }

        [Authorize]
        public IActionResult Confirm(int ticketId)
        {
            Ticket ticketConfirm = _ticketsRepository.FindByID(ticketId);
            if (ticketConfirm != null)
            {
                ticketConfirm.Status = StatusTicket.Waiting_Payment;
                Order order = _ordersRepository
                    .GetAll()
                    .FirstOrDefault(o => o.Ticket.Id == ticketId);
                order.Status = StatusOrder.Confirmed;
                _ordersRepository.Update(order);
                _ticketsRepository.Update(ticketConfirm);
            }
            return RedirectToAction("GetMyTickets");
        }

        [Authorize]
        public IActionResult Reject(int ticketId, string messageReject)
        {
            Ticket ticketReject = _ticketsRepository.FindByID(ticketId);
            if (ticketReject != null)
            {
                ticketReject.Status = StatusTicket.Selling;
                Order order = _ordersRepository
                    .GetAll()
                    .FirstOrDefault(o => o.Ticket.Id == ticketId);
                order.Status = StatusOrder.Rejected;
                order.MessageReject = messageReject;

                _ordersRepository.Update(order);
                _ticketsRepository.Update(ticketReject);
            }
            return RedirectToAction("GetMyTickets");
        }

        [Authorize]
        [HttpPost]
        public IActionResult ToOrder(int ticketId, int evId)
        {
            Ticket ticket = _ticketsRepository.FindByID(ticketId);
            ticket.Status = StatusTicket.Waiting_Confirmation;
            _ticketsRepository.Update(ticket);
            _ordersRepository.CreateNewOrder(ticket, User.Identity.Name);
            return RedirectToAction("ListTickets", new { eventId = evId});
        }
    }
}

task2/Trukhan.TicketReSailing/Trukhan.TicketReSailing.Presentation/Views/Home/Index.cshtml
@using Trukhan.TicketReSailing.Business.Interfaces
@using Trukhan.TicketReSailing.Business.Models
@using Microsoft.AspNetCore.Mvc.Localization

@model IEventRepository

@inject IViewLocalizer Localizer

@{ 
   ViewData["Title"] = Localizer["Events"];
}

<div>
    @foreach (Event m in Model.GetAll())
    {
     <div class="event">
	  <form method="get" asp-controller="Ticket" asp-action="ListTickets" asp-route-returnUrl="@Context.Request.Path">		
        <div class="date-name-ticket">
            @Localizer[@m.Date.ToString("d")]
        </div>
        <a class="date-name-ticket" asp-controller="Ticket" asp-action="ListTickets" asp-route-eventId="@m.Id"> 
          <div class="name-ticket">@Localizer[@m.Name]</div>
        </a>
        <div class="info-event">
          <div class="img-content-size">
            <input type="hidden" name="eventId" value="@m.Id" />
            <input type="image" src="~/Pictures/@m.Banner" height="200" width="200"/>
          </div>
          <div class="attr-event">
            <div class="content">
              <div class="left-content">
                  <span class="p-table">@Localizer["City:"]</span>
              </div>
              <div class="right-content">
                  <span class="p-table">@Localizer[@m.Venue.City.Name]</span>
              </div>
            </div>
            <div class="content">
              <div class="left-content">
                  <span class="p-table">@Localizer["Venue:"]</span>
              </div>
              <div class="right-content">
                <span class="p-table">@Localizer[@m.Venue.Name]</span>
              </div>
            </div>
            <div class="content">
              <div class="left-content">
                <span class="p-table">@Localizer["Adress:"]</span>
              </div>
              <div class="right-content">
                  <span class="p-table">@Localizer[@m.Venue.Address]</span>
              </div>
            </div>
            <div class="content">
              <div class="left-content">
                  <span class="p-table">@Localizer["Description:"]</span>
              </div>
              <div class="right-content">
                  <span class="p-table">@Localizer[@m.Description]</span>
              </div>
            </div>
          </div>  
        </div>
      </form>
 </div>
 <div class="div-float-none"></div>
 <br>    
}
</div>