task2/Trukhan.TicketReSailing/Trukhan.TicketReSailing.Presentation/Controllers/AdminController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Trukhan.TicketReSailing.Business.Models;
using Trukhan.TicketReSailing.Business.Repositories;
using System.Security.Claims;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Trukhan.TicketReSailing.Business.Interfaces;
using Microsoft.AspNetCore.Identity;
using Trukhan.TicketReSailing.Presentation.ViewModels;
using System;
using System.Linq;
using Microsoft.Extensions.Localization;

namespace Trukhan.TicketReSailing.Presentation.Controllers
{   
    [Authorize(Roles="admin")]
    public class AdminController : Controller
    {

        public AdminController(IEventRepository eventRepository, IVenueRepository venueRepository, ICityRepository cityRepository, IStringLocalizer<AdminController> localizer)
        {
            _eventRepository = eventRepository;
            _venueRepository= venueRepository;
            _cityRepository= cityRepository;
		    _localizer = localizer;
        }

        private IEventRepository _eventRepository;
        private IVenueRepository _venueRepository;
        private ICityRepository _cityRepository;
	    private IStringLocalizer<AdminController> _localizer;

        [HttpGet]
        public IActionResult Index (int id)
        {
            switch (id)
            {
                case 1: 
                    ViewBag.NamePage = _localizer["EditingCities"];
                    return View("~/Views/ListsEntities/ViewCities.cshtml", _cityRepository);
                case 2: 
                    ViewBag.NamePage = _localizer["EditingVenues"];
                    return View("~/Views/ListsEntities/ViewVenues.cshtml", _venueRepository);
                default: 
                    ViewBag.NamePage = _localizer["EditingEvents"];
                    return View("~/Views/ListsEntities/ViewEvents.cshtml", _eventRepository);
            }
        }

        public IActionResult Create (int idEntity)
        {
            switch (idEntity)
            {
                case 1: return View("~/Views/EditingListEntities/ViewCreateCity.cshtml");
                case 2:
                    ViewBag.Cities = _cityRepository.GetAll();
                    return View("~/Views/EditingListEntities/ViewCreateVenue.cshtml");

                default:
                    ViewBag.Venues = _venueRepository.GetAll(); 
                    return View("~/Views/EditingListEntities/ViewCreateEvent.cshtml");
            }
        }

        public IActionResult CreateCity(NewCityViewModel model, int idEntity)
        {
            if (ModelState.IsValid)
            {
                City city = new City{Name = model.Name};
                _cityRepository.Add(city);
            }
            else
            {
                return RedirectToAction("Create", new { idEntity = idEntity });
            }
            return RedirectToAction("Index", new { id = idEntity });
        }

        public IActionResult CreateVenue(NewVenueViewModel model, int idEntity, int cityId)
        {
            if (ModelState.IsValid)
            {   
                City city = _cityRepository.FindById(cityId);
                Venue venue = new Venue 
                { 
                    Name = model.Name,
                    Address = model.Address,
                    City = city,
                };
                _venueRepository.Add(venue);
            }
            else
            {
                return RedirectToAction("Create", new { idEntity = idEntity });
            }
            return RedirectToAction("Index", new { id = idEntity });
        }

        public IActionResult CreateEvent (NewEventViewModel model, int idEntity, int venueId)
        {
            if (ModelState.IsValid)
            {
                Venue venue = _venueRepository.FindById(venueId);
                Event ev = new Event
                {
                    Name = model.Name,
                    Date = DateTime.Parse(model.Date),
                    Venue = venue,
                    Banner = model.Banner,
                    Description = model.Description,
                };
                _eventRepository.Add(ev);
            }
            else
            {
                return RedirectToAction("Create", new { idEntity = idEntity });
            }
            return RedirectToAction("Index", new { id = idEntity });
        }

        [HttpGet]
        public IActionResult Update(int id, int idEntity)
        {
            switch (idEntity)
            {
                case 1:
                    City city = _cityRepository.FindById(id);
                    if (city != null)
                        return View("~/Views/EditingListEntities/ViewUpdateCity.cshtml", city);
                    break;
                case 2:
                    Venue venue = _venueRepository.FindById(id);
                    if (venue != null)
                        ViewBag.Cities = _cityRepository.GetAll();
                        return View("~/Views/EditingListEntities/ViewUpdateVenue.cshtml", venue);
                    break;
                case 3: 
                    Event ev = _eventRepository.FindById(id);
                    if (ev != null)
                        ViewBag.Venues = _venueRepository.GetAll();
                        return View("~/Views/EditingListEntities/ViewUpdateEvent.cshtml", ev);
                    break;
            }
            return RedirectToAction("Index", new { id = idEntity });
        }

        [HttpPost]
        public IActionResult UpdateCity(City city)
        {
            _cityRepository.Update(city);            
            return RedirectToAction("Index", new { id = 1 });
        }

        [HttpPost]
        public IActionResult UpdateVenue(Venue venue, int cityId)
        {
            City city = _cityRepository.FindById(cityId);
            venue.City = city;
            _venueRepository.Update(venue);
            return RedirectToAction("Index", new { id = 2 });
        }

        [HttpPost]
        public IActionResult UpdateEvent(Event ev, int venueId)
        {
            Venue venue = _venueRepository.FindById(venueId);
            ev.Venue = venue;
            _eventRepository.Update(ev);
            return RedirectToAction("Index", new { id = 3 });
        }

        public IActionResult Delete(int id, int idEntity)
        {
            switch(idEntity)    
            {
                case 1:
                    City city = _cityRepository.FindById(id);
                    if (city != null)
                        _cityRepository.Delete(city);
                    break;
                case 2:
                    Venue venue = _venueRepository.FindById(id);
                    if (venue != null)
                        _venueRepository.Delete(venue);
                    break;
                case 3:
                    Event ev = _eventRepository.FindById(id);
                    if (ev != null)
                        _eventRepository.Delete(ev);
                    break;
            }
            return RedirectToAction("Index", new {id = idEntity});
        }   
        
 
    }
}

task2/Trukhan.TicketReSailing/Trukhan.TicketReSailing.Presentation/Controllers/AdminUserController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Trukhan.TicketReSailing.Business.Models;
using Trukhan.TicketReSailing.Business.Repositories;
using System.Security.Claims;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Trukhan.TicketReSailing.Business.Interfaces;
using Microsoft.AspNetCore.Identity;
using Trukhan.TicketReSailing.Presentation.ViewModels;
using System;
using System.Linq;
using Microsoft.Extensions.Localization;

namespace Trukhan.TicketReSailing.Presentation.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminUserController : Controller
    {

        public AdminUserController(IUserRepository userRepository, IStringLocalizer<AdminUserController> localizer)
        {
            _userRepository = userRepository;
            _localizer = localizer;
        }

        private IUserRepository _userRepository;
        private IStringLocalizer<AdminUserController> _localizer;

        [HttpGet]
        public IActionResult ViewUsers()
        {
            List<User> users = _userRepository.GetAllUsers();
            return View(users);
        }


        public IActionResult AddRole(string userId, string userRole)
        {
            User user = _userRepository.FindByUserIdAsync(userId).Result;
            bool result = _userRepository.AddToRole(user, userRole);
            if (result)
            {
                ViewData["Message"] = String.Format("Роль {0} для пользователя {1} успешно добавлена", userRole, user.UserName);
            }
            else
            {
                ViewData["Message"] = String.Format("Роль {0} для пользователя {1} не была добавлена", userRole, user.UserName);
            }
            return RedirectToAction("ViewUsers");
        }

        public IActionResult RemoveRole(string userId, string userRole)
        {
            User user = _userRepository.FindByUserIdAsync(userId).Result;
            bool result = _userRepository.RemoveRole(user, userRole);
            if (result)
            {
                ViewBag.Message = String.Format("Роль {0} у пользователя {1} успешно удалена", userRole, user.UserName);
            }
            else
            {
                ViewBag.Message = String.Format("Роль {0} у пользователя {1} не была удалена", userRole, user.UserName);
            }
            return RedirectToAction("ViewUsers");
        }
    }
}

task2/Trukhan.TicketReSailing/Trukhan.TicketReSailing.Presentation/Views/Shared/_Authorized.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer   

<div>
      <div>
        <div class="user-name">
          <h3>@ViewBag.UserName</h3>
        </div>
        <div class="role-name">
          <h4>@ViewBag.RoleName</h4>
        </div>
     </div>
      <div class="reset-float"></div>
      <div class="button-logout">
        <form asp-controller="Account" asp-action="Logout">
          <input type="submit" value=@Localizer["Logout"]>
        </form>
      </div>
      @{
          if (User.IsInRole("admin"))
          {
            <div class="group-links">
              <a class="like-button" asp-controller="AdminUser" asp-action="ViewUsers">@Localizer["Administration Accounts"]</a>
			  <a class="like-button" asp-controller="Admin" asp-action="Index" asp-route-id="1">@Localizer["Administration records Cities"]</a>
              <a class="like-button" asp-controller="Admin" asp-action="Index" asp-route-id="2">@Localizer["Administration records Venues"]</a>
              <a class="like-button" asp-controller="Admin" asp-action="Index" asp-route-id="3">@Localizer["Administration records Events"]</a>
            </div>
          }
       }
          <div class="group-button">
            <form>
             <button formaction="~/Order/GetMyOrders">@Localizer["My Orders"]</button>
             <button formaction="~/Ticket/GetMyTickets">@Localizer["My Tickets"]</button>
              <button formaction="~/User/GetUserInfo">@Localizer["User Info"]</button>
            </form>
          </div>
</div>

task2/Trukhan.TicketReSailing/Trukhan.TicketReSailing.Presentation/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@Localizer["TicketsReSailing"] - @ViewData["Title"]</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/css/StyleSheet.css" />
    </environment>
</head>

<body>
  <header>
    <div class="div-home-return">
        <a asp-controller ="Home" asp-action="Index"><img class="img-home" src="Pictures/home.jpg"/></a>
    </div>
    <div class="div-select-language">
      @await Html.PartialAsync("_SelectLanguagePartial")
    </div>
    @{ 
        if (User.Identity.IsAuthenticated)
        {
            ViewBag.NamePartial = "_Authorized";

            ViewBag.UserName = User.Identity.Name;

            if (User.IsInRole("admin"))
            {
                ViewBag.RoleName = "Admin";
            }
            if (User.IsInRole("user"))
            {
                ViewBag.RoleName = "User";
            }
        }
        else
        {
            ViewBag.NamePartial = "_LoginOrRegister";
        }
    }
    <div class="reset-float"></div>
    
    @Html.Partial((string)@ViewBag.NamePartial)    
    
    <div class="reset-float"></div>
    <div>
        <p class="p-name-page">@ViewBag.NamePage</p>
    </div>
  </header>
    <hr />
  <div class="body-content">
      @RenderBody()
      <hr />
    <footer>
      <div style="float:left">
       <p>&copy; 2016 - @Localizer["Andrei Trukhan"]</p>
      </div>
    </footer>
  </div>
</body>
</html>

task2/Trukhan.TicketReSailing/Trukhan.TicketReSailing.Presentation/Views/Shared/_LoginOrRegister.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<div>
    <form method="get">
        <input type="hidden" name="returnUrl" value="@Context.Request.Path"/>
        <input type="submit" formaction="~/Account/Login" value=@Localizer["Login"]/>
        <button formaction="~/Account/Register">@Localizer["Register"]</button>
    </form>   
</div>

task2/Trukhan.TicketReSailing/Trukhan.TicketReSailing.Presentation/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions


@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.EnglishName })
        .ToList();
}

<div title="Request culture provider" @requestCulture?.Provider?.GetType().Name>
    <form id="selectLanguage" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
          method="post" class="form-horizontal" role="form">
        @Localizer["Language:"] 
        <select name="culture" onchange="this.form.submit()" asp-for="@requestCulture.RequestCulture.UICulture.Name"  asp-items="cultureItems"></select>
    </form>
</div>